# Configuration pour actions/labeler
frontend:
  - components/**/*
  - pages/**/*
  - assets/**/*
  - layouts/**/*

backend-nuxt:
  - server/**/*

logic:
  - stores/**/*
  - composables/**/*
  - utils/**/*

config:
  - nuxt.config.ts
  - tailwind.config.ts
  - package.json
  - .github/workflows/**/*
